# Generated by Django 6.0.5 on 2026-05-24 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(unique=True, verbose_name='회차')),
                ('numbers', models.JSONField(verbose_name='당첨 번호')),
                ('bonus_number', models.PositiveIntegerField(verbose_name='보너스 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추첨일')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(verbose_name='회차')),
                ('numbers', models.JSONField(verbose_name='선택 번호')),
                ('pick_type', models.CharField(choices=[('MANUAL', '수동'), ('AUTO', '자동')], max_length=10, verbose_name='구매 방식')),
                ('price', models.PositiveIntegerField(default=1000, verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='구매일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WinningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_count', models.PositiveIntegerField(verbose_name='일치 개수')),
                ('bonus_match', models.BooleanField(default=False, verbose_name='보너스 일치')),
                ('rank', models.CharField(max_length=20, verbose_name='등수')),
                ('prize_amount', models.PositiveIntegerField(default=0, verbose_name='당첨금')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='확인일')),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.draw')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotto.ticket')),
            ],
        ),
    ]
